### ISSUE TITLE
Repo is empty

### ISSUE THREAD

**Issue by niarbrnd** [chegewara/usb-v2-esp-idf-examples#1]
Please add example for idf

**Comment by chegewara** [comment]
Hi,
due to some initial complication which is related to fact that arduino is using different version of tinyusb and esp-idf different (mostly menuconfig flags) i decided to abandon the idea to make one library for both options.
Because of that the is no usable esp-idf version and for some time it wont be, but i may decide to make new USB library for esp-idf when i play a bit more with P4.

**Comment by niarbrnd** [comment]
Thanks for answer.

**Comment by niarbrnd** [comment]
I only need the usbhidkeyboard function, is there a simplified example for such a task?

**Comment by chegewara** [comment]
With my library this should be fine, as long as esp-idf v2 library is working
https://github.com/chegewara/EspTinyUSB/tree/master/examples/device/hid/keyboard

You can try espressif esp-idf hid example, which is C and should be easy to work with
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/device/tusb_hid

Or just examples from tinyusb library
https://github.com/hathach/tinyusb/tree/master/examples/device
